//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 01:33:29 PM CEST 
//
package com.msopentech.odatajclient.engine.data.metadata.edmx.mapping.cs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.msopentech.odatajclient.engine.data.metadata.edmx.mapping.cs package.
 * <p>An ObjectFactory allows you to programmatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Mapping_QNAME = new QName("http://schemas.microsoft.com/ado/2009/11/mapping/cs",
            "Mapping");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * com.msopentech.odatajclient.engine.data.metadata.edmx.mapping.cs
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TFunctionImportCondition }
     *
     */
    public FunctionImportCondition createTFunctionImportCondition() {
        return new FunctionImportCondition();
    }

    /**
     * Create an instance of {@link TComplexProperty }
     *
     */
    public ComplexProperty createTComplexProperty() {
        return new ComplexProperty();
    }

    /**
     * Create an instance of {@link TEntitySetMapping }
     *
     */
    public EntitySetMapping createTEntitySetMapping() {
        return new EntitySetMapping();
    }

    /**
     * Create an instance of {@link TEntityTypeModificationFunctionMapping }
     *
     */
    public EntityTypeModificationFunctionMapping createTEntityTypeModificationFunctionMapping() {
        return new EntityTypeModificationFunctionMapping();
    }

    /**
     * Create an instance of {@link TAlias }
     *
     */
    public Alias createTAlias() {
        return new Alias();
    }

    /**
     * Create an instance of {@link TModificationFunctionMappingAssociationEnd }
     *
     */
    public ModificationFunctionMappingAssociationEnd createTModificationFunctionMappingAssociationEnd() {
        return new ModificationFunctionMappingAssociationEnd();
    }

    /**
     * Create an instance of {@link TMapping }
     *
     */
    public Mapping createTMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link TFunctionImportMapping }
     *
     */
    public FunctionImportMapping createTFunctionImportMapping() {
        return new FunctionImportMapping();
    }

    /**
     * Create an instance of {@link TEntityContainerMapping }
     *
     */
    public EntityContainerMapping createTEntityContainerMapping() {
        return new EntityContainerMapping();
    }

    /**
     * Create an instance of {@link TMappingFragment }
     *
     */
    public MappingFragment createTMappingFragment() {
        return new MappingFragment();
    }

    /**
     * Create an instance of {@link TEntityTypeMapping }
     *
     */
    public EntityTypeMapping createTEntityTypeMapping() {
        return new EntityTypeMapping();
    }

    /**
     * Create an instance of {@link TEntityTypeModificationFunctionWithResult }
     *
     */
    public EntityTypeModificationFunctionWithResult createTEntityTypeModificationFunctionWithResult() {
        return new EntityTypeModificationFunctionWithResult();
    }

    /**
     * Create an instance of {@link TEndProperty }
     *
     */
    public EndProperty createTEndProperty() {
        return new EndProperty();
    }

    /**
     * Create an instance of {@link TResultBinding }
     *
     */
    public ResultBinding createTResultBinding() {
        return new ResultBinding();
    }

    /**
     * Create an instance of {@link TComplexTypeMapping }
     *
     */
    public ComplexTypeMapping createTComplexTypeMapping() {
        return new ComplexTypeMapping();
    }

    /**
     * Create an instance of {@link TModificationFunctionMappingScalarProperty }
     *
     */
    public ModificationFunctionMappingScalarProperty createTModificationFunctionMappingScalarProperty() {
        return new ModificationFunctionMappingScalarProperty();
    }

    /**
     * Create an instance of {@link TAssociationSetModificationFunctionMapping }
     *
     */
    public AssociationSetModificationFunctionMapping createTAssociationSetModificationFunctionMapping() {
        return new AssociationSetModificationFunctionMapping();
    }

    /**
     * Create an instance of {@link TEntityTypeModificationFunction }
     *
     */
    public EntityTypeModificationFunction createTEntityTypeModificationFunction() {
        return new EntityTypeModificationFunction();
    }

    /**
     * Create an instance of {@link TFunctionImportEntityTypeMapping }
     *
     */
    public FunctionImportEntityTypeMapping createTFunctionImportEntityTypeMapping() {
        return new FunctionImportEntityTypeMapping();
    }

    /**
     * Create an instance of {@link TModificationFunctionMappingEndProperty }
     *
     */
    public ModificationFunctionMappingEndProperty createTModificationFunctionMappingEndProperty() {
        return new ModificationFunctionMappingEndProperty();
    }

    /**
     * Create an instance of {@link TModificationFunctionMappingComplexProperty }
     *
     */
    public ModificationFunctionMappingComplexProperty createTModificationFunctionMappingComplexProperty() {
        return new ModificationFunctionMappingComplexProperty();
    }

    /**
     * Create an instance of {@link TFunctionImportComplexTypeMapping }
     *
     */
    public FunctionImportComplexTypeMapping createTFunctionImportComplexTypeMapping() {
        return new FunctionImportComplexTypeMapping();
    }

    /**
     * Create an instance of {@link TScalarProperty }
     *
     */
    public ScalarProperty createTScalarProperty() {
        return new ScalarProperty();
    }

    /**
     * Create an instance of {@link TQueryView }
     *
     */
    public QueryView createTQueryView() {
        return new QueryView();
    }

    /**
     * Create an instance of {@link TFunctionImportMappingResultMapping }
     *
     */
    public FunctionImportMappingResultMapping createTFunctionImportMappingResultMapping() {
        return new FunctionImportMappingResultMapping();
    }

    /**
     * Create an instance of {@link TCondition }
     *
     */
    public Condition createTCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link TAssociationSetMapping }
     *
     */
    public AssociationSetMapping createTAssociationSetMapping() {
        return new AssociationSetMapping();
    }

    /**
     * Create an instance of {@link TAssociationSetModificationFunction }
     *
     */
    public AssociationSetModificationFunction createTAssociationSetModificationFunction() {
        return new AssociationSetModificationFunction();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMapping }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2009/11/mapping/cs", name = "Mapping")
    public JAXBElement<Mapping> createMapping(Mapping value) {
        return new JAXBElement<Mapping>(_Mapping_QNAME, Mapping.class, null, value);
    }
}
