//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 01:33:29 PM CEST 
//
package com.msopentech.odatajclient.engine.data.metadata.edmx.mapping.cs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.msopentech.odatajclient.engine.data.metadata.edmx.mapping.cs package.
 * <p>An ObjectFactory allows you to programmatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Mapping_QNAME = new QName("http://schemas.microsoft.com/ado/2009/11/mapping/cs",
            "Mapping");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * com.msopentech.odatajclient.engine.data.metadata.edmx.mapping.cs
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TFunctionImportCondition }
     *
     */
    public TFunctionImportCondition createTFunctionImportCondition() {
        return new TFunctionImportCondition();
    }

    /**
     * Create an instance of {@link TComplexProperty }
     *
     */
    public TComplexProperty createTComplexProperty() {
        return new TComplexProperty();
    }

    /**
     * Create an instance of {@link TEntitySetMapping }
     *
     */
    public TEntitySetMapping createTEntitySetMapping() {
        return new TEntitySetMapping();
    }

    /**
     * Create an instance of {@link TEntityTypeModificationFunctionMapping }
     *
     */
    public TEntityTypeModificationFunctionMapping createTEntityTypeModificationFunctionMapping() {
        return new TEntityTypeModificationFunctionMapping();
    }

    /**
     * Create an instance of {@link TAlias }
     *
     */
    public TAlias createTAlias() {
        return new TAlias();
    }

    /**
     * Create an instance of {@link TModificationFunctionMappingAssociationEnd }
     *
     */
    public TModificationFunctionMappingAssociationEnd createTModificationFunctionMappingAssociationEnd() {
        return new TModificationFunctionMappingAssociationEnd();
    }

    /**
     * Create an instance of {@link TMapping }
     *
     */
    public TMapping createTMapping() {
        return new TMapping();
    }

    /**
     * Create an instance of {@link TFunctionImportMapping }
     *
     */
    public TFunctionImportMapping createTFunctionImportMapping() {
        return new TFunctionImportMapping();
    }

    /**
     * Create an instance of {@link TEntityContainerMapping }
     *
     */
    public TEntityContainerMapping createTEntityContainerMapping() {
        return new TEntityContainerMapping();
    }

    /**
     * Create an instance of {@link TMappingFragment }
     *
     */
    public TMappingFragment createTMappingFragment() {
        return new TMappingFragment();
    }

    /**
     * Create an instance of {@link TEntityTypeMapping }
     *
     */
    public TEntityTypeMapping createTEntityTypeMapping() {
        return new TEntityTypeMapping();
    }

    /**
     * Create an instance of {@link TEntityTypeModificationFunctionWithResult }
     *
     */
    public TEntityTypeModificationFunctionWithResult createTEntityTypeModificationFunctionWithResult() {
        return new TEntityTypeModificationFunctionWithResult();
    }

    /**
     * Create an instance of {@link TEndProperty }
     *
     */
    public TEndProperty createTEndProperty() {
        return new TEndProperty();
    }

    /**
     * Create an instance of {@link TResultBinding }
     *
     */
    public TResultBinding createTResultBinding() {
        return new TResultBinding();
    }

    /**
     * Create an instance of {@link TComplexTypeMapping }
     *
     */
    public TComplexTypeMapping createTComplexTypeMapping() {
        return new TComplexTypeMapping();
    }

    /**
     * Create an instance of {@link TModificationFunctionMappingScalarProperty }
     *
     */
    public TModificationFunctionMappingScalarProperty createTModificationFunctionMappingScalarProperty() {
        return new TModificationFunctionMappingScalarProperty();
    }

    /**
     * Create an instance of {@link TAssociationSetModificationFunctionMapping }
     *
     */
    public TAssociationSetModificationFunctionMapping createTAssociationSetModificationFunctionMapping() {
        return new TAssociationSetModificationFunctionMapping();
    }

    /**
     * Create an instance of {@link TEntityTypeModificationFunction }
     *
     */
    public TEntityTypeModificationFunction createTEntityTypeModificationFunction() {
        return new TEntityTypeModificationFunction();
    }

    /**
     * Create an instance of {@link TFunctionImportEntityTypeMapping }
     *
     */
    public TFunctionImportEntityTypeMapping createTFunctionImportEntityTypeMapping() {
        return new TFunctionImportEntityTypeMapping();
    }

    /**
     * Create an instance of {@link TModificationFunctionMappingEndProperty }
     *
     */
    public TModificationFunctionMappingEndProperty createTModificationFunctionMappingEndProperty() {
        return new TModificationFunctionMappingEndProperty();
    }

    /**
     * Create an instance of {@link TModificationFunctionMappingComplexProperty }
     *
     */
    public TModificationFunctionMappingComplexProperty createTModificationFunctionMappingComplexProperty() {
        return new TModificationFunctionMappingComplexProperty();
    }

    /**
     * Create an instance of {@link TFunctionImportComplexTypeMapping }
     *
     */
    public TFunctionImportComplexTypeMapping createTFunctionImportComplexTypeMapping() {
        return new TFunctionImportComplexTypeMapping();
    }

    /**
     * Create an instance of {@link TScalarProperty }
     *
     */
    public TScalarProperty createTScalarProperty() {
        return new TScalarProperty();
    }

    /**
     * Create an instance of {@link TQueryView }
     *
     */
    public TQueryView createTQueryView() {
        return new TQueryView();
    }

    /**
     * Create an instance of {@link TFunctionImportMappingResultMapping }
     *
     */
    public TFunctionImportMappingResultMapping createTFunctionImportMappingResultMapping() {
        return new TFunctionImportMappingResultMapping();
    }

    /**
     * Create an instance of {@link TCondition }
     *
     */
    public TCondition createTCondition() {
        return new TCondition();
    }

    /**
     * Create an instance of {@link TAssociationSetMapping }
     *
     */
    public TAssociationSetMapping createTAssociationSetMapping() {
        return new TAssociationSetMapping();
    }

    /**
     * Create an instance of {@link TAssociationSetModificationFunction }
     *
     */
    public TAssociationSetModificationFunction createTAssociationSetModificationFunction() {
        return new TAssociationSetModificationFunction();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TMapping }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/ado/2009/11/mapping/cs", name = "Mapping")
    public JAXBElement<TMapping> createMapping(TMapping value) {
        return new JAXBElement<TMapping>(_Mapping_QNAME, TMapping.class, null, value);
    }
}
